# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node: [10.7.0, 10.x, 11.x, 12.x, 13.x, 14.x]
        os:
          [windows-2019, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.0.1
      - name: install node tools
        if: matrix.os == 'windows-2019'
        # windows-build-tools@5.2.2 failed to install, so we use 4.0.0
        run: npm install --global --production windows-build-tools@4.0.0
      - name: install node-gyp
        if: matrix.os == 'windows-2019'
        run: npm install --global node-gyp@latest
      - name: Set node config to use python2.7
        if: matrix.os == 'windows-2019'
        run: npm config set python python2.7
      - name: Set node config to set msvs_version to 2015
        if: matrix.os == 'windows-2019'
        run: npm config set msvs_version 2015
      - run: npm ci
      - run: npm test
        env:
          FORCE_COLOR: 1
